In [ ]:
s = "apple,banana,cherry,dates"


substrings = s.split(',')
result = ' '.join(substrings)
result